title: Personal Second Brain
description: A personal knowledge management system to capture and organize your thoughts.
author: Your Name
baseurl: "" # Leave empty for GitHub Pages root
url: "https://<your-github-username>.github.io/<repository-name>" # Update with your GitHub Pages URL
theme: minima # Or any other theme you want to use
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
